export const TARGET_SITES = [
  "https://smartstore.naver.com/campride",
  "https://smartstore.naver.com/tobystore",
  "https://smartstore.naver.com/farmland02",
  "https://smartstore.naver.com/clubdiyz",
  "https://smartstore.naver.com/oncorporation",
  "https://smartstore.naver.com/joannainri",
  "https://smartstore.naver.com/archiva",
  "https://smartstore.naver.com/msstor",
  "https://smartstore.naver.com/sellnbuy35",
  "https://smartstore.naver.com/jjin-shopping",
  "https://smartstore.naver.com/marketthej",
  "https://smartstore.naver.com/hyuncar",
  "https://smartstore.naver.com/sinbad",
  "https://smartstore.naver.com/bamocar",
  "https://smartstore.naver.com/stylebonwash",
  "https://smartstore.naver.com/campride",
  "https://smartstore.naver.com/youngfactory",
  "https://smartstore.naver.com/kakaohotdeal",
  "https://smartstore.naver.com/seatosummit",
  "https://smartstore.naver.com/off-roadkorea",
  "https://smartstore.naver.com/tuning-33",
  "https://smartstore.naver.com/gaiacamper",
  "https://smartstore.naver.com/lifebasket_official",
  "https://smartstore.naver.com/campingriver",
  "https://smartstore.naver.com/monoholic",
  "https://smartstore.naver.com/smartlife1",
  "https://smartstore.naver.com/koreaoverlander",
  "https://smartstore.naver.com/thulecompany",
  "https://smartstore.naver.com/eightsix",
  "https://smartstore.naver.com/929support",
  "https://smartstore.naver.com/woongki",
  "https://smartstore.naver.com/artone",
  "https://smartstore.naver.com/6jyo",
  "https://smartstore.naver.com/yoonesk",
  "https://smartstore.naver.com/autofactory1",
  "https://smartstore.naver.com/juncarrier",
  "https://smartstore.naver.com/seomka",
  "https://smartstore.naver.com/0776s",
  "https://smartstore.naver.com/knbox",
  "https://smartstore.naver.com/thule",
  "https://smartstore.naver.com/iguanabike",
  "https://smartstore.naver.com/myride",
  "https://smartstore.naver.com/junauto",
  "https://smartstore.naver.com/rdtiger",
  "https://smartstore.naver.com/wdrwd",
  "https://smartstore.naver.com/youilcarrier",
  "https://smartstore.naver.com/funnyke",
  "https://smartstore.naver.com/every1day",
  "https://smartstore.naver.com/piterrack",
  "https://smartstore.naver.com/iandyouwo",
  "https://smartstore.naver.com/nuri-space",
  "https://smartstore.naver.com/daitsomallshop",
  "https://smartstore.naver.com/jeremyamy",
  "https://smartstore.naver.com/shfkddl6kies",
  "https://smartstore.naver.com/mkvitamin",
  "https://smartstore.naver.com/campingapp",
  "https://smartstore.naver.com/xlite",
  "https://smartstore.naver.com/campingstay",
  "https://smartstore.naver.com/thulemall",
  "https://smartstore.naver.com/trapoverland1",
  "https://smartstore.naver.com/stylecar",
  "https://smartstore.naver.com/savecamping",
  "https://smartstore.naver.com/ilnamshoppingcenter",
  "https://smartstore.naver.com/polygon",
  "https://smartstore.naver.com/oneiro",
  "https://smartstore.naver.com/carbark",
  "https://smartstore.naver.com/09car",
  "https://smartstore.naver.com/sweet_car",
  "https://smartstore.naver.com/global4u",
  "https://smartstore.naver.com/da1_",
  "https://smartstore.naver.com/chabagi",
  "https://smartstore.naver.com/awesomemat",
  "https://smartstore.naver.com/dadamat",
  "https://smartstore.naver.com/danwon",
  "https://smartstore.naver.com/nweawesomeamall",
  "https://smartstore.naver.com/carsuppliesmarket",
  "https://smartstore.naver.com/dongwoo-industry",
  "https://smartstore.naver.com/naobiz",
  "https://smartstore.naver.com/0jamall",
  "https://smartstore.naver.com/jy110",
  "https://smartstore.naver.com/lthr",
  "https://smartstore.naver.com/dmcmworld",
  "https://smartstore.naver.com/chuchoice",
  "https://smartstore.naver.com/alldaypick",
  "https://smartstore.naver.com/mathouse",
  "https://smartstore.naver.com/dhstyleshop",
  "https://smartstore.naver.com/arcadecode",
  "https://smartstore.naver.com/waterport",
  "https://smartstore.naver.com/visentium",
];

export const FILE_PATH = '/Users/duckyounglee/Downloads/업체리스트.xlsx';
export const PAGE_MAX = 20;

export const HEADER_ROW = [
  {
    value: '서비스명',
  },
  {
    value: '가격',
  },
  {
    value: '카테고리1',
  },
  {
    value: '카테고리2',
  },
  {
    value: '랭글러 업체리스트',
  },
  {
    value: '사이트',
  },
];